version: 2

models:
  - name: stg_taxi_trips
    description: Cleaned taxi trips
    columns:
      - name: pickup_ts
        tests: [not_null]
      - name: total_amount_usd
        tests:
          - dbt_utils.expression_is_true:
              name: non_negative_total_amount_or_null
              arguments:
                expression: "total_amount_usd is null or total_amount_usd >= -5"

  - name: stg_weather
    description: Daily NYC weather
    columns:
      - name: weather_date
        tests: [unique, not_null]
